"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { StatusBadge } from "@/app/components/status-badge";
import { Notification } from "@/app/components/notification";
import { TRAVEL_SEGMENT_TYPES, TRIP_STATUSES } from "@/lib/trips";

type Item = { id: number; date?: string; time?: string; type?: string; title: string; description: string; startLocation?: string; destination?: string; journey?: string; autoGenerated?: boolean };
type Media = { id: number; name: string; size: number };
type Notice = { type: "success" | "warning" | "error"; text: string };
type TripSectionsProps = {
  tripId: number;
  description: string;
  notes: string;
  destination: string;
  startLocation: string;
  tripDirection: string | null;
  returnNeedsRegeneration: boolean;
  statuses: Record<"overview" | "itinerary" | "travel" | "documents" | "photos", string>;
  itinerary: Item[];
  segments: Item[];
  documents: Media[];
  photos: Media[];
};

function StatusSelect({ name, value }: { name: string; value: string }) {
  return (
    <select className="border rounded p-2" defaultValue={value} name={name}>
      {TRIP_STATUSES.map((status) => <option key={status}>{status}</option>)}
    </select>
  );
}

export function TripSections(props: TripSectionsProps) {
  const router = useRouter();
  const [notice, setNotice] = useState<Notice | null>(null);
  const [pendingAction, setPendingAction] = useState("");
  const [confirmingMediaDelete, setConfirmingMediaDelete] = useState("");
  const [confirmingRegeneration, setConfirmingRegeneration] = useState(false);
  const [confirmingItineraryPopulation, setConfirmingItineraryPopulation] = useState(false);
  const pending = Boolean(pendingAction);
  const endpoint = `/api/trips/${props.tripId}/sections`;
  const outboundSegments = props.segments.filter((segment) => segment.journey !== "RETURN");
  const returnSegments = props.segments.filter((segment) => segment.journey === "RETURN");

  async function jsonRequest(method: string, body: Record<string, unknown>, successMessage: string) {
    setNotice(null);
    setPendingAction("save");
    try {
      const response = await fetch(endpoint, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = (await response.json().catch(() => null)) as { error?: string } | null;
      if (!response.ok) throw new Error(data?.error ?? "Unable to save changes");
      setNotice({ type: "success", text: successMessage });
      router.refresh();
      return true;
    } catch (requestError) {
      setNotice({ type: "error", text: requestError instanceof Error ? requestError.message : "Unable to save changes" });
      return false;
    } finally {
      setPendingAction("");
    }
  }

  function fields(form: HTMLFormElement) {
    return Object.fromEntries(new FormData(form).entries());
  }

  async function submitForm(event: FormEvent<HTMLFormElement>, action: string, method = "PATCH", successMessage?: string) {
    event.preventDefault();
    await jsonRequest(
      method,
      { action, ...fields(event.currentTarget) },
      successMessage ?? (action === "sectionStatus" ? "Section status updated successfully" : "Changes saved successfully")
    );
  }

  async function populateItinerary(mode: "add" | "replace", confirm: boolean) {
    const saved = await jsonRequest(
      "PATCH",
      { action: "populateItinerary", mode, confirm },
      mode === "replace" ? "Itinerary replaced from travel." : "Travel added to itinerary."
    );
    if (saved) setConfirmingItineraryPopulation(false);
  }

  async function upload(event: FormEvent<HTMLFormElement>, kind: "documents" | "photos") {
    event.preventDefault();
    const form = event.currentTarget;
    const file = new FormData(form).get("file");
    const media = kind === "documents" ? props.documents : props.photos;
    const totalStorage = [...props.documents, ...props.photos].reduce((total, item) => total + item.size, 0);
    if (!(file instanceof File)) return;
    if (file.size > 5 * 1024 * 1024) {
      setNotice({ type: "warning", text: `${kind === "documents" ? "Document" : "Photo"} must be 5 MB or smaller` });
      return;
    }
    if (media.length >= (kind === "documents" ? 15 : 25)) {
      setNotice({ type: "warning", text: `Maximum ${kind === "documents" ? 15 : 25} ${kind} per trip` });
      return;
    }
    if (totalStorage + file.size > 200 * 1024 * 1024) {
      setNotice({ type: "warning", text: "Maximum 200 MB storage per trip" });
      return;
    }
    setNotice(null);
    setPendingAction(`upload-${kind}`);
    try {
      const response = await fetch(`/api/trips/${props.tripId}/media/${kind}`, {
        method: "POST",
        body: new FormData(form),
      });
      const data = (await response.json().catch(() => null)) as { error?: string } | null;
      if (!response.ok) throw new Error(data?.error ?? "Upload failed");
      if (form.isConnected) form.reset();
      setNotice({ type: "success", text: kind === "documents" ? "Document uploaded successfully" : "Photo uploaded successfully" });
      router.refresh();
    } catch (uploadError) {
      const text = uploadError instanceof Error ? uploadError.message : "Upload failed";
      const isLimit = text.includes("5 MB") || text.startsWith("Maximum");
      setNotice({ type: isLimit ? "warning" : "error", text });
    } finally {
      setPendingAction("");
    }
  }

  async function removeMedia(kind: "documents" | "photos", id: number) {
    setNotice(null);
    setPendingAction("delete-media");
    try {
      const response = await fetch(`/api/trips/${props.tripId}/media/${kind}/${id}`, { method: "DELETE" });
      if (!response.ok) throw new Error(`Unable to delete ${kind === "documents" ? "document" : "photo"}`);
      setNotice({ type: "success", text: `${kind === "documents" ? "Document" : "Photo"} deleted successfully` });
      setConfirmingMediaDelete("");
      router.refresh();
    } catch (deleteError) {
      setNotice({ type: "error", text: deleteError instanceof Error ? deleteError.message : "Unable to delete file" });
    } finally {
      setPendingAction("");
    }
  }

  return (
    <div className="mt-10 grid gap-8">
      {notice && <Notification message={notice.text} type={notice.type} />}

      <section className="order-0 border rounded-lg p-6">
        <header className="flex justify-between gap-4 mb-4"><h2 className="text-2xl font-bold">Overview</h2><StatusBadge status={props.statuses.overview} /></header>
        <form className="grid gap-4" onSubmit={(event) => submitForm(event, "overview")}>
          <input className="border p-2 rounded" defaultValue={props.destination} name="destination" placeholder="Destination" />
          <textarea className="border p-2 rounded" defaultValue={props.description} name="description" placeholder="Description" rows={4} />
          <textarea className="border p-2 rounded" defaultValue={props.notes} name="notes" placeholder="Notes" rows={3} />
          <div className="flex gap-3"><StatusSelect name="status" value={props.statuses.overview} /><button className="bg-blue-600 text-white px-4 py-2 rounded" disabled={pending}>Save Overview</button></div>
        </form>
      </section>

      <section className="order-2 border rounded-lg p-6">
        <header className="flex justify-between gap-4 mb-4"><h2 className="text-2xl font-bold">Itinerary</h2><StatusBadge status={props.statuses.itinerary} /></header>
        <form className="flex gap-3 mb-5" onSubmit={(event) => submitForm(event, "sectionStatus")}>
          <input name="section" type="hidden" value="itinerary" /><StatusSelect name="status" value={props.statuses.itinerary} /><button className="border px-4 rounded" disabled={pending}>Update Status</button>
        </form>
        <form className="grid sm:grid-cols-2 gap-3 mb-6" onSubmit={(event) => submitForm(event, "itinerary", "POST")}>
          <input className="border p-2" name="date" required type="date" /><input className="border p-2" name="time" required type="time" />
          <input className="border p-2 sm:col-span-2" name="title" placeholder="Title" required /><textarea className="border p-2 sm:col-span-2" name="description" placeholder="Description" />
          <button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending}>Add Item</button>
        </form>
        <div className="grid gap-3">{props.itinerary.map((item) => (
          <form className="grid sm:grid-cols-2 gap-2 border rounded p-4" key={item.id} onSubmit={(event) => submitForm(event, "itinerary", "PATCH", "Itinerary item saved.")}>
            <input name="itemId" type="hidden" value={item.id} /><input className="border p-2" defaultValue={item.date} name="date" required type="date" /><input className="border p-2" defaultValue={item.time} name="time" required type="time" />
            <input className="border p-2 sm:col-span-2" defaultValue={item.title} name="title" required /><textarea className="border p-2 sm:col-span-2" defaultValue={item.description} name="description" />
            <div className="flex gap-2"><button className="border px-3 py-1 rounded" disabled={pending}>Save</button><button className="text-red-600" disabled={pending} onClick={() => jsonRequest("DELETE", { action: "itinerary", itemId: item.id }, "Itinerary item deleted.")} type="button">Delete</button></div>
          </form>
        ))}</div>
      </section>

      <section className="order-1 border rounded-lg p-6">
        <header className="flex justify-between gap-4 mb-4"><h2 className="text-2xl font-bold">Travel</h2><StatusBadge status={props.statuses.travel} /></header>
        <form className="grid sm:grid-cols-2 gap-3 mb-6" onSubmit={(event) => submitForm(event, "travel")}>
          <input className="border p-2" defaultValue={props.startLocation} name="startLocation" placeholder="Start location" /><input className="border p-2" defaultValue={props.destination} name="destination" placeholder="Destination" />
          <label className="grid gap-1"><span className="text-sm font-medium">Trip Direction</span><select className="border p-2" defaultValue={props.tripDirection ?? ""} name="tripDirection" required><option disabled value="">Choose direction</option><option value="ONE_WAY">One-Way</option><option value="ROUND_TRIP">Round Trip</option></select></label>
          <StatusSelect name="status" value={props.statuses.travel} /><button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending}>Save Travel</button>
        </form>
        {!props.tripDirection && <Notification className="mb-6" message="Choose One-Way or Round Trip and save travel information before adding segments." type="warning" />}
        {props.tripDirection === "ROUND_TRIP" && props.returnNeedsRegeneration && <div className="mb-6 rounded-md border border-amber-300 bg-amber-50 p-4 text-amber-900"><p className="mb-3">Outbound journey changed. You can regenerate the return trip, but existing return edits will only be replaced after confirmation.</p>{confirmingRegeneration ? <div><p className="font-semibold mb-3">Replace all current return segments with newly generated ones?</p><div className="flex gap-3"><button className="bg-amber-700 text-white px-4 py-2 rounded" disabled={pending} onClick={async () => { await jsonRequest("PATCH", { action: "regenerateReturn", confirm: true }, "Return journey regenerated successfully"); setConfirmingRegeneration(false); }} type="button">Confirm Regeneration</button><button className="border border-amber-700 px-4 py-2 rounded" disabled={pending} onClick={() => setConfirmingRegeneration(false)} type="button">Cancel</button></div></div> : <button className="border border-amber-700 px-4 py-2 rounded disabled:opacity-60" disabled={pending} onClick={() => setConfirmingRegeneration(true)} type="button">Regenerate Return Trip</button>}</div>}
        <h3 className="text-xl font-semibold mb-3">Outbound Journey</h3>
        <form className="grid sm:grid-cols-2 gap-3 mb-6" onSubmit={(event) => submitForm(event, "segment", "POST")}>
          <select className="border p-2" name="type">{TRAVEL_SEGMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</select><input className="border p-2" name="title" placeholder="Segment title" required />
          <input className="border p-2" name="date" type="date" /><input className="border p-2" name="time" type="time" /><input className="border p-2" name="startLocation" placeholder="From" /><input className="border p-2" name="destination" placeholder="To" />
          <textarea className="border p-2 sm:col-span-2" name="description" placeholder="Details" /><button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending || !props.tripDirection}>Add Segment</button>
        </form>
        <div className="grid gap-3">{outboundSegments.map((item, index) => (
          <form className="grid sm:grid-cols-2 gap-2 border rounded p-4" key={item.id} onSubmit={(event) => submitForm(event, "segment")}>
            <input name="itemId" type="hidden" value={item.id} /><select className="border p-2" defaultValue={item.type} name="type">{TRAVEL_SEGMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</select><input className="border p-2" defaultValue={item.title} name="title" required />
            <input className="border p-2" defaultValue={item.date} name="date" type="date" /><input className="border p-2" defaultValue={item.time} name="time" type="time" /><input className="border p-2" defaultValue={item.startLocation} name="startLocation" placeholder="From" /><input className="border p-2" defaultValue={item.destination} name="destination" placeholder="To" />
            <textarea className="border p-2 sm:col-span-2" defaultValue={item.description} name="description" /><div className="flex flex-wrap gap-2"><button className="border px-3 py-1 rounded" disabled={pending}>Save</button><button className="border px-3 py-1 rounded" disabled={pending || index === 0} onClick={() => jsonRequest("PATCH", { action: "reorderSegment", itemId: item.id, direction: "up" }, "Outbound segment moved successfully")} type="button">Move Up</button><button className="border px-3 py-1 rounded" disabled={pending || index === outboundSegments.length - 1} onClick={() => jsonRequest("PATCH", { action: "reorderSegment", itemId: item.id, direction: "down" }, "Outbound segment moved successfully")} type="button">Move Down</button><button className="text-red-600" disabled={pending} onClick={() => jsonRequest("DELETE", { action: "segment", itemId: item.id }, "Travel segment deleted successfully")} type="button">Delete</button></div>
          </form>
        ))}</div>
        {props.tripDirection === "ROUND_TRIP" && <div className="mt-8"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><h3 className="text-xl font-semibold">Return Journey</h3>{!returnSegments.length && outboundSegments.length > 0 && <button className="border px-4 py-2 rounded" disabled={pending} onClick={() => jsonRequest("PATCH", { action: "regenerateReturn" }, "Return journey generated successfully")} type="button">Generate Return Journey</button>}</div><div className="grid gap-3">{returnSegments.map((item) => <form className="grid sm:grid-cols-2 gap-2 border rounded p-4" key={item.id} onSubmit={(event) => submitForm(event, "segment")}><input name="itemId" type="hidden" value={item.id} /><select className="border p-2" defaultValue={item.type} name="type">{TRAVEL_SEGMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</select><input className="border p-2" defaultValue={item.title} name="title" required />{item.autoGenerated && <span className="w-fit rounded bg-blue-100 px-2 py-1 text-xs font-medium text-blue-800 sm:col-span-2">Generated from outbound journey</span>}<input className="border p-2" defaultValue={item.date} name="date" type="date" /><input className="border p-2" defaultValue={item.time} name="time" type="time" /><input className="border p-2" defaultValue={item.startLocation} name="startLocation" placeholder="From" /><input className="border p-2" defaultValue={item.destination} name="destination" placeholder="To" /><textarea className="border p-2 sm:col-span-2" defaultValue={item.description} name="description" /><div className="flex gap-2"><button className="border px-3 py-1 rounded" disabled={pending}>Save</button><button className="text-red-600" disabled={pending} onClick={() => jsonRequest("DELETE", { action: "segment", itemId: item.id }, "Return segment deleted successfully")} type="button">Delete</button></div></form>)}</div></div>}
        {props.segments.length > 0 && <div className="mt-8 border-t pt-6"><h3 className="text-lg font-semibold mb-2">Populate Itinerary</h3><p className="text-sm text-gray-600 mb-3">Create editable itinerary items from the travel method, route, date, and time.</p>{props.itinerary.length === 0 ? <button className="border px-4 py-2 rounded" disabled={pending} onClick={() => populateItinerary("add", false)} type="button">Create Itinerary from Travel</button> : confirmingItineraryPopulation ? <div className="rounded-md border border-amber-300 bg-amber-50 p-4 text-amber-900"><p className="mb-3">Your itinerary already has items. Add travel items or replace the existing itinerary?</p><div className="flex flex-wrap gap-3"><button className="border border-amber-700 px-4 py-2 rounded" disabled={pending} onClick={() => populateItinerary("add", true)} type="button">Add Travel Items</button><button className="bg-amber-700 text-white px-4 py-2 rounded" disabled={pending} onClick={() => populateItinerary("replace", true)} type="button">Replace Itinerary</button><button className="border px-4 py-2 rounded" disabled={pending} onClick={() => setConfirmingItineraryPopulation(false)} type="button">Cancel</button></div></div> : <button className="border px-4 py-2 rounded" disabled={pending} onClick={() => setConfirmingItineraryPopulation(true)} type="button">Populate Itinerary from Travel</button>}</div>}
      </section>

      {(["documents", "photos"] as const).map((kind) => {
        const media = kind === "documents" ? props.documents : props.photos;
        return <section className="order-3 border rounded-lg p-6" key={kind}>
          <header className="flex justify-between gap-4 mb-4"><h2 className="text-2xl font-bold capitalize">{kind}</h2><StatusBadge status={props.statuses[kind]} /></header>
          <form className="flex flex-wrap gap-3 mb-4" onSubmit={(event) => submitForm(event, "sectionStatus")}><input name="section" type="hidden" value={kind} /><StatusSelect name="status" value={props.statuses[kind]} /><button className="border px-4 rounded" disabled={pending}>Update Status</button></form>
          <form className="flex flex-wrap gap-3 mb-5" onSubmit={(event) => upload(event, kind)}><input accept={kind === "documents" ? "application/pdf" : "image/jpeg,image/png,image/webp,image/gif"} name="file" required type="file" /><button className="bg-blue-600 text-white px-4 py-2 rounded" disabled={pending}>{pendingAction === `upload-${kind}` ? "Uploading..." : "Upload"}</button></form>
          <div className={kind === "photos" ? "grid grid-cols-2 sm:grid-cols-3 gap-4" : "grid gap-2"}>{media.map((file) => <div className="border rounded p-3" key={file.id}>
            {kind === "photos" && <Image alt={file.name} className="w-full h-32 object-cover rounded mb-2" height={128} src={`/api/trips/${props.tripId}/media/photos/${file.id}`} unoptimized width={200} />}
            <a className="text-blue-700 break-all" href={`/api/trips/${props.tripId}/media/${kind}/${file.id}`}>{file.name}</a><p className="text-xs text-gray-500">{Math.ceil(file.size / 1024)} KB</p><button className="text-red-600 text-sm mt-2" disabled={pending} onClick={() => setConfirmingMediaDelete(`${kind}-${file.id}`)} type="button">Delete</button>
            {confirmingMediaDelete === `${kind}-${file.id}` && <div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><p>Delete this {kind === "documents" ? "document" : "photo"}?</p><div className="flex gap-2 mt-2"><button className="bg-red-600 text-white px-3 py-1 rounded" disabled={pending} onClick={() => removeMedia(kind, file.id)} type="button">Confirm</button><button className="border px-3 py-1 rounded" disabled={pending} onClick={() => setConfirmingMediaDelete("")} type="button">Cancel</button></div></div>}
          </div>)}</div>
        </section>;
      })}
    </div>
  );
}
