"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState, type FormEvent, type ReactNode } from "react";
import { Notification } from "@/app/components/notification";
import { isDateWithinTrip, tripDateRangeError, TRAVEL_SEGMENT_TYPES } from "@/lib/trips";
import type { TripSummaryEntry } from "@/lib/trip-summary";

type Item = { id: number; date?: string; time?: string; type?: string; title: string; description: string; startLocation?: string; destination?: string; direction?: string; returnForSegmentId?: number | null; autoGenerated?: boolean };
type Media = { id: number; name: string; size: number };
type NoticeScope = "global" | "overview" | "travel" | "itinerary" | "documents" | "photos";
type Notice = { type: "success" | "warning" | "error"; text: string; scope: NoticeScope; target?: string };
type TripSectionsProps = {
  tripId: number;
  tripStartDate: string;
  tripEndDate: string;
  description: string;
  notes: string;
  destination: string;
  startLocation: string;
  tripSummary: TripSummaryEntry[];
  tripSummaryIsCustom: boolean;
  generatedTripSummary: TripSummaryEntry[];
  itinerary: Item[];
  segments: Item[];
  documents: Media[];
  photos: Media[];
  updatesSection: ReactNode;
  pollsSection: ReactNode;
};

export function TripSections(props: TripSectionsProps) {
  const router = useRouter();
  const [notice, setNotice] = useState<Notice | null>(null);
  const [pendingAction, setPendingAction] = useState("");
  const [confirmingMediaDelete, setConfirmingMediaDelete] = useState("");
  const [confirmingItineraryPopulation, setConfirmingItineraryPopulation] = useState(false);
  const [tripSummary, setTripSummary] = useState(props.tripSummary);
  const [selectedFiles, setSelectedFiles] = useState<Record<"documents" | "photos", string>>({ documents: "", photos: "" });
  const pending = Boolean(pendingAction);
  const endpoint = `/api/trips/${props.tripId}/sections`;

  async function jsonRequest(method: string, body: Record<string, unknown>, successMessage: string, scope: NoticeScope = "global", target?: string) {
    setNotice(null);
    setPendingAction("save");
    try {
      const response = await fetch(endpoint, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = (await response.json().catch(() => null)) as { error?: string } | null;
      if (!response.ok) throw new Error(data?.error ?? "Unable to save changes");
      setNotice({ type: "success", text: successMessage, scope, target });
      setTimeout(() => router.refresh(), 0);
      return true;
    } catch (requestError) {
      setNotice({ type: "error", text: requestError instanceof Error ? requestError.message : "Unable to save changes", scope, target });
      return false;
    } finally {
      setPendingAction("");
    }
  }

  function fields(form: HTMLFormElement) {
    return Object.fromEntries(new FormData(form).entries());
  }

  function validateSectionDate(value: string, scope: "travel" | "itinerary", target: string) {
    if (value && !isDateWithinTrip(value, props.tripStartDate, props.tripEndDate)) {
      setNotice({ type: "error", text: tripDateRangeError(props.tripStartDate, props.tripEndDate), scope, target });
    } else if (notice?.target === target && notice.type === "error") {
      setNotice(null);
    }
  }

  async function submitForm(event: FormEvent<HTMLFormElement>, action: string, method = "PATCH", successMessage?: string) {
    event.preventDefault();
    const formElement = event.currentTarget;
    const formFields = fields(formElement);
    const scope: NoticeScope = action === "itinerary"
      ? "itinerary"
      : action === "travel" || action === "segment"
        ? "travel"
        : action === "overview"
          ? "overview"
          : "global";
    const target = action === "itinerary"
      ? `itinerary-${formFields.itemId ?? "new"}`
      : action === "travel"
        ? "travel"
        : action === "segment"
          ? `segment-${formFields.itemId ?? "new"}`
          : undefined;
    const submittedDate = typeof formFields.date === "string" ? formFields.date : "";
    if ((action === "itinerary" || action === "segment")
      && submittedDate
      && !isDateWithinTrip(submittedDate, props.tripStartDate, props.tripEndDate)) {
      setNotice({
        type: "error",
        text: tripDateRangeError(props.tripStartDate, props.tripEndDate),
        scope,
        target,
      });
      return;
    }
    const saved = await jsonRequest(
      method,
      { action, ...formFields },
      successMessage ?? "Saved.",
      scope,
      target
    );
    if (saved && method === "POST" && formElement.isConnected) formElement.reset();
  }

  async function saveTripSummary() {
    const entries = [...tripSummary].sort((left, right) => left.date.localeCompare(right.date));
    const saved = await jsonRequest("PATCH", { action: "tripSummary", entries }, "Trip summary saved.", "overview");
    if (saved) setTripSummary(entries);
  }

  async function regenerateTripSummary() {
    const saved = await jsonRequest("PATCH", { action: "tripSummary", entries: null }, "Trip summary regenerated.", "overview");
    if (saved) setTripSummary(props.generatedTripSummary);
  }

  async function populateItinerary(mode: "add" | "replace", confirm: boolean) {
    const saved = await jsonRequest(
      "PATCH",
      { action: "populateItinerary", mode, confirm },
      mode === "replace" ? "Itinerary replaced from travel." : "Travel added to itinerary.",
      "travel"
    );
    if (saved) setConfirmingItineraryPopulation(false);
  }

  async function upload(event: FormEvent<HTMLFormElement>, kind: "documents" | "photos") {
    event.preventDefault();
    const form = event.currentTarget;
    const file = new FormData(form).get("file");
    const media = kind === "documents" ? props.documents : props.photos;
    const totalStorage = [...props.documents, ...props.photos].reduce((total, item) => total + item.size, 0);
    if (!(file instanceof File)) return;
    if (file.size > 5 * 1024 * 1024) {
      setNotice({ type: "warning", text: `${kind === "documents" ? "Document" : "Photo"} must be 5 MB or smaller`, scope: kind });
      return;
    }
    if (media.length >= (kind === "documents" ? 15 : 25)) {
      setNotice({ type: "warning", text: `Maximum ${kind === "documents" ? 15 : 25} ${kind} per trip`, scope: kind });
      return;
    }
    if (totalStorage + file.size > 200 * 1024 * 1024) {
      setNotice({ type: "warning", text: "Maximum 200 MB storage per trip", scope: kind });
      return;
    }
    setNotice(null);
    setPendingAction(`upload-${kind}`);
    try {
      const response = await fetch(`/api/trips/${props.tripId}/media/${kind}`, {
        method: "POST",
        body: new FormData(form),
      });
      const data = (await response.json().catch(() => null)) as { error?: string } | null;
      if (!response.ok) throw new Error(data?.error ?? "Upload failed");
      if (form.isConnected) form.reset();
      setSelectedFiles((current) => ({ ...current, [kind]: "" }));
      setNotice({ type: "success", text: kind === "documents" ? "Document uploaded successfully" : "Photo uploaded successfully", scope: kind });
      router.refresh();
    } catch (uploadError) {
      const text = uploadError instanceof Error ? uploadError.message : "Upload failed";
      const isLimit = text.includes("5 MB") || text.startsWith("Maximum");
      setNotice({ type: isLimit ? "warning" : "error", text, scope: kind });
    } finally {
      setPendingAction("");
    }
  }

  async function removeMedia(kind: "documents" | "photos", id: number) {
    setNotice(null);
    setPendingAction("delete-media");
    try {
      const response = await fetch(`/api/trips/${props.tripId}/media/${kind}/${id}`, { method: "DELETE" });
      if (!response.ok) throw new Error(`Unable to delete ${kind === "documents" ? "document" : "photo"}`);
      setNotice({ type: "success", text: `${kind === "documents" ? "Document" : "Photo"} deleted.`, scope: kind });
      setConfirmingMediaDelete("");
      router.refresh();
    } catch (deleteError) {
      setNotice({ type: "error", text: deleteError instanceof Error ? deleteError.message : "Unable to delete file", scope: kind });
    } finally {
      setPendingAction("");
    }
  }

  return (
    <div className="mt-10 grid gap-8">
      {notice?.scope === "global" && <Notification message={notice.text} type={notice.type} />}

      <section className="order-0 border rounded-lg p-6" id="overview">
        <h2 className="text-2xl font-bold mb-4">Overview</h2>
        {notice?.scope === "overview" && <Notification className="mb-4" message={notice.text} type={notice.type} />}
        <form className="grid gap-4" onSubmit={(event) => submitForm(event, "overview", "PATCH", "Overview saved.")}>
          <input className="border p-2 rounded" defaultValue={props.destination} name="destination" placeholder="Destination" />
          <textarea className="border p-2 rounded" defaultValue={props.description} name="description" placeholder="Description" rows={4} />
          <textarea className="border p-2 rounded" defaultValue={props.notes} name="notes" placeholder="Notes" rows={3} />
          <button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending}>Save Overview</button>
        </form>
        <div className="mt-6 border-t pt-5">
          <div className="flex flex-wrap items-start justify-between gap-3 mb-3"><div><h3 className="text-xl font-bold">Trip Summary</h3><p className="text-sm text-gray-600">Major daily milestones derived from Travel and Itinerary. Edit the generated wording as needed.</p></div>{props.tripSummaryIsCustom && <span className="rounded bg-blue-100 px-2 py-1 text-xs font-medium text-blue-800">Customized</span>}</div>
          <div className="grid gap-3">{tripSummary.map((entry, index) => <div className="grid gap-2 sm:grid-cols-[9rem_1fr_auto]" key={`${entry.date}-${index}`}><input aria-label={`Summary date ${index + 1}`} className="border p-2 rounded" onChange={(event) => setTripSummary((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, date: event.target.value } : item))} type="date" value={entry.date} /><input aria-label={`Summary milestone ${index + 1}`} className="border p-2 rounded" maxLength={120} onChange={(event) => setTripSummary((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} value={entry.title} /><button className="text-red-600 px-2" disabled={pending} onClick={() => setTripSummary((current) => current.filter((_, itemIndex) => itemIndex !== index))} type="button">Remove</button></div>)}</div>
          <div className="flex flex-wrap gap-3 mt-4"><button className="border px-4 py-2 rounded" disabled={pending} onClick={() => setTripSummary((current) => [...current, { date: current.at(-1)?.date ?? props.generatedTripSummary.at(-1)?.date ?? "", title: "" }])} type="button">Add Milestone</button><button className="bg-blue-600 text-white px-4 py-2 rounded" disabled={pending || tripSummary.some((entry) => !entry.date || !entry.title.trim())} onClick={saveTripSummary} type="button">Save Trip Summary</button><button className="border px-4 py-2 rounded" disabled={pending} onClick={regenerateTripSummary} type="button">Regenerate from Travel &amp; Itinerary</button></div>
        </div>
      </section>

      <div className="order-1" id="updates">{props.updatesSection}</div>

      <section className="order-3 border rounded-lg p-6" id="itinerary">
        <h2 className="text-2xl font-bold mb-4">Itinerary</h2>
        {notice?.scope === "itinerary" && !notice.target && <Notification className="mb-4" message={notice.text} type={notice.type} />}
        <form className="grid sm:grid-cols-2 gap-3 mb-6" onSubmit={(event) => submitForm(event, "itinerary", "POST", "Itinerary item saved.")}>
          {notice?.target === "itinerary-new" && <Notification className="sm:col-span-2" message={notice.text} type={notice.type} />}
          <input className="border p-2" max={props.tripEndDate} min={props.tripStartDate} name="date" onChange={(event) => validateSectionDate(event.target.value, "itinerary", "itinerary-new")} required type="date" /><input className="border p-2" name="time" required type="time" />
          <input className="border p-2 sm:col-span-2" name="title" placeholder="Title" required /><textarea className="border p-2 sm:col-span-2" name="description" placeholder="Description" />
          <button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending}>Add Item</button>
        </form>
        <div className="grid gap-3">{props.itinerary.map((item) => (
          <form className="grid sm:grid-cols-2 gap-2 border rounded p-4" key={item.id} onSubmit={(event) => submitForm(event, "itinerary", "PATCH", "Itinerary item saved.")}>
            {notice?.target === `itinerary-${item.id}` && <Notification className="sm:col-span-2" message={notice.text} type={notice.type} />}
            <input name="itemId" type="hidden" value={item.id} /><input className="border p-2" defaultValue={item.date} max={props.tripEndDate} min={props.tripStartDate} name="date" onChange={(event) => validateSectionDate(event.target.value, "itinerary", `itinerary-${item.id}`)} required type="date" /><input className="border p-2" defaultValue={item.time} name="time" required type="time" />
            <input className="border p-2 sm:col-span-2" defaultValue={item.title} name="title" required /><textarea className="border p-2 sm:col-span-2" defaultValue={item.description} name="description" />
            <div className="flex gap-2"><button className="border px-3 py-1 rounded" disabled={pending}>Save</button><button className="text-red-600" disabled={pending} onClick={() => jsonRequest("DELETE", { action: "itinerary", itemId: item.id }, "Itinerary item deleted.")} type="button">Delete</button></div>
          </form>
        ))}</div>
      </section>

      <section className="order-2 border rounded-lg p-6" id="travel">
        <h2 className="text-2xl font-bold mb-4">Travel</h2>
        {notice?.scope === "travel" && !notice.target && <Notification className="mb-4" message={notice.text} type={notice.type} />}
        <form className="grid sm:grid-cols-2 gap-3 mb-6" onSubmit={(event) => submitForm(event, "travel", "PATCH", "Travel saved.")}>
          {notice?.target === "travel" && <Notification className="sm:col-span-2" message={notice.text} type={notice.type} />}
          <input className="border p-2" defaultValue={props.startLocation} name="startLocation" placeholder="Start location" /><input className="border p-2" defaultValue={props.destination} name="destination" placeholder="Destination" />
          <button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending}>Save Travel</button>
        </form>
        <h3 className="text-xl font-semibold mb-3">Add Travel Segment</h3>
        <form className="grid sm:grid-cols-2 gap-3 mb-6" onSubmit={(event) => submitForm(event, "segment", "POST", "Travel saved.")}>
          {notice?.target === "segment-new" && <Notification className="sm:col-span-2" message={notice.text} type={notice.type} />}
          <select className="border p-2" name="type">{TRAVEL_SEGMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</select><input className="border p-2" name="title" placeholder="Segment title" required />
          <input className="border p-2" max={props.tripEndDate} min={props.tripStartDate} name="date" onChange={(event) => validateSectionDate(event.target.value, "travel", "segment-new")} type="date" /><input className="border p-2" name="time" type="time" /><input className="border p-2" name="startLocation" placeholder="From" /><input className="border p-2" name="destination" placeholder="To" />
          <label className="grid gap-1"><span className="text-sm font-medium">Direction</span><select className="border p-2" defaultValue="ONE_WAY" name="direction"><option value="ONE_WAY">One-Way</option><option value="ROUND_TRIP">Round Trip</option></select></label>
          <textarea className="border p-2 sm:col-span-2" name="description" placeholder="Details" /><button className="bg-blue-600 text-white px-4 py-2 rounded w-fit" disabled={pending}>Add Segment</button>
        </form>
        <h3 className="text-xl font-semibold mb-3">Travel Segments</h3>
        <div className="grid gap-3">{props.segments.map((item, index) => (
          <form className="grid sm:grid-cols-2 gap-2 border rounded p-4" key={item.id} onSubmit={(event) => submitForm(event, "segment", "PATCH", "Travel saved.")}>
            {notice?.target === `segment-${item.id}` && <Notification className="sm:col-span-2" message={notice.text} type={notice.type} />}
            <input name="itemId" type="hidden" value={item.id} /><select className="border p-2" defaultValue={item.type} name="type">{TRAVEL_SEGMENT_TYPES.map((type) => <option key={type}>{type}</option>)}</select><input className="border p-2" defaultValue={item.title} name="title" required />
            {item.returnForSegmentId && <span className="w-fit rounded bg-blue-100 px-2 py-1 text-xs font-medium text-blue-800 sm:col-span-2">Generated return segment</span>}
            <input className="border p-2" defaultValue={item.date} max={props.tripEndDate} min={props.tripStartDate} name="date" onChange={(event) => validateSectionDate(event.target.value, "travel", `segment-${item.id}`)} type="date" /><input className="border p-2" defaultValue={item.time} name="time" type="time" /><input className="border p-2" defaultValue={item.startLocation} name="startLocation" placeholder="From" /><input className="border p-2" defaultValue={item.destination} name="destination" placeholder="To" />
            <label className="grid gap-1"><span className="text-sm font-medium">Direction</span><select className="border p-2" defaultValue={item.direction ?? "ONE_WAY"} name="direction"><option value="ONE_WAY">One-Way</option><option value="ROUND_TRIP">Round Trip</option></select></label>
            <textarea className="border p-2 sm:col-span-2" defaultValue={item.description} name="description" /><div className="flex flex-wrap gap-2"><button className="border px-3 py-1 rounded" disabled={pending}>Save</button><button className="border px-3 py-1 rounded" disabled={pending || index === 0} onClick={() => jsonRequest("PATCH", { action: "reorderSegment", itemId: item.id, direction: "up" }, "Travel segment moved successfully")} type="button">Move Up</button><button className="border px-3 py-1 rounded" disabled={pending || index === props.segments.length - 1} onClick={() => jsonRequest("PATCH", { action: "reorderSegment", itemId: item.id, direction: "down" }, "Travel segment moved successfully")} type="button">Move Down</button><button className="text-red-600" disabled={pending} onClick={() => jsonRequest("DELETE", { action: "segment", itemId: item.id }, "Travel segment deleted.")} type="button">Delete</button></div>
          </form>
        ))}</div>
        {props.segments.length > 0 && <div className="mt-8 border-t pt-6"><h3 className="text-lg font-semibold mb-2">Populate Itinerary</h3><p className="text-sm text-gray-600 mb-3">Create editable itinerary items from the travel method, route, date, and time.</p>{props.itinerary.length === 0 ? <button className="border px-4 py-2 rounded" disabled={pending} onClick={() => populateItinerary("add", false)} type="button">Create Itinerary from Travel</button> : confirmingItineraryPopulation ? <div className="rounded-md border border-amber-300 bg-amber-50 p-4 text-amber-900"><p className="mb-3">Your itinerary already has items. Add travel items or replace the existing itinerary?</p><div className="flex flex-wrap gap-3"><button className="border border-amber-700 px-4 py-2 rounded" disabled={pending} onClick={() => populateItinerary("add", true)} type="button">Add Travel Items</button><button className="bg-amber-700 text-white px-4 py-2 rounded" disabled={pending} onClick={() => populateItinerary("replace", true)} type="button">Replace Itinerary</button><button className="border px-4 py-2 rounded" disabled={pending} onClick={() => setConfirmingItineraryPopulation(false)} type="button">Cancel</button></div></div> : <button className="border px-4 py-2 rounded" disabled={pending} onClick={() => setConfirmingItineraryPopulation(true)} type="button">Populate Itinerary from Travel</button>}</div>}
      </section>

      {(["documents", "photos"] as const).map((kind) => {
        const media = kind === "documents" ? props.documents : props.photos;
        return <section className={`${kind === "documents" ? "order-4" : "order-5"} border rounded-lg p-6`} id={kind} key={kind}>
          <h2 className="text-2xl font-bold capitalize mb-4">{kind}</h2>
          {notice?.scope === kind && <Notification className="mb-4" message={notice.text} type={notice.type} />}
          <form className="flex flex-wrap items-start gap-3 mb-5" onSubmit={(event) => upload(event, kind)}>
            <div>
              <input
                accept={kind === "documents" ? "application/pdf" : "image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif,image/avif"}
                className="peer sr-only"
                id={`${kind}-file`}
                name="file"
                onChange={(event) => setSelectedFiles((current) => ({ ...current, [kind]: event.target.files?.[0]?.name ?? "" }))}
                required
                type="file"
              />
              <label className="inline-block cursor-pointer rounded border px-4 py-2 font-medium peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-blue-600" htmlFor={`${kind}-file`}>Select File</label>
              <p aria-live="polite" className="mt-2 max-w-xs break-all text-sm text-gray-600">{selectedFiles[kind] || "No file selected"}</p>
            </div>
            <button className="bg-blue-600 text-white px-4 py-2 rounded" disabled={pending}>{pendingAction === `upload-${kind}` ? "Uploading..." : "Upload"}</button>
          </form>
          <div className={kind === "photos" ? "grid grid-cols-2 sm:grid-cols-3 gap-4" : "grid gap-2"}>{media.map((file) => <div className="border rounded p-3" key={file.id}>
            {kind === "photos" && <Image alt={file.name} className="w-full h-32 object-cover rounded mb-2" height={128} src={`/api/trips/${props.tripId}/media/photos/${file.id}`} unoptimized width={200} />}
            <a className="text-blue-700 break-all" href={`/api/trips/${props.tripId}/media/${kind}/${file.id}`}>{file.name}</a><p className="text-xs text-gray-500">{Math.ceil(file.size / 1024)} KB</p><button className="text-red-600 text-sm mt-2" disabled={pending} onClick={() => setConfirmingMediaDelete(`${kind}-${file.id}`)} type="button">Delete</button>
            {confirmingMediaDelete === `${kind}-${file.id}` && <div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><p>Delete this {kind === "documents" ? "document" : "photo"}?</p><div className="flex gap-2 mt-2"><button className="bg-red-600 text-white px-3 py-1 rounded" disabled={pending} onClick={() => removeMedia(kind, file.id)} type="button">Confirm</button><button className="border px-3 py-1 rounded" disabled={pending} onClick={() => setConfirmingMediaDelete("")} type="button">Cancel</button></div></div>}
          </div>)}</div>
        </section>;
      })}
      <div className="order-6" id="polls">{props.pollsSection}</div>
    </div>
  );
}
