import { beforeEach, describe, expect, it, vi } from "vitest";
import { prisma } from "@/lib/prisma";
import { createOwner, createTrip, jsonRequest, params, resetDatabase } from "./helpers";

const state = vi.hoisted(() => ({ userId: 0, tripId: 0 }));
vi.mock("@/lib/auth", () => ({ verifyToken: vi.fn(async () => ({ userId: state.userId, email: "test@example.com" })) }));
vi.mock("@/lib/trip-access", () => ({
  getOwnedTripId: vi.fn(async (tripId: number) => ({
    session: { userId: state.userId, email: "test@example.com" },
    tripId: tripId === state.tripId ? tripId : null,
  })),
}));

import { POST as createTripRoute } from "@/app/api/trips/route";
import { PATCH as updateTripRoute } from "@/app/api/trips/[id]/route";
import { PATCH as patchSections, POST as postSections } from "@/app/api/trips/[id]/sections/route";
import { PATCH as patchCommunity, POST as postCommunity } from "@/app/api/trips/[id]/community/route";
import { POST as uploadMedia } from "@/app/api/trips/[id]/media/[kind]/route";
import { GET as getPublicMedia } from "@/app/api/public/[token]/media/[kind]/[mediaId]/route";

beforeEach(async () => {
  await resetDatabase();
  const owner = await createOwner();
  state.userId = owner.id;
  state.tripId = 0;
});

describe("PostgreSQL-backed core workflows", () => {
  it("creates and publishes a trip through production API routes", async () => {
    const created = await createTripRoute(jsonRequest("POST", {
      tripName: "Alaska Cruise", tripType: "Cruise", startDate: "2026-06-26",
      endDate: "2026-07-06", travelerCount: 2,
    }));
    expect(created.status).toBe(201);
    const trip = (await created.json()).trip;
    state.tripId = trip.id;

    const published = await updateTripRoute(jsonRequest("PATCH", { isPublished: true }), params(trip.id));
    expect(published.status).toBe(200);
    expect((await prisma.trip.findUniqueOrThrow({ where: { id: trip.id } })).isPublished).toBe(true);

    const unpublished = await updateTripRoute(jsonRequest("PATCH", { isPublished: false }), params(trip.id));
    expect(unpublished.status).toBe(200);
    expect((await prisma.trip.findUniqueOrThrow({ where: { id: trip.id } })).isPublished).toBe(false);
  });

  it("generates a constrained return segment and propagates travel into itinerary", async () => {
    const trip = await createTrip(state.userId);
    state.tripId = trip.id;
    const response = await postSections(jsonRequest("POST", {
      action: "segment", type: "Flight", title: "Flight to Seattle", date: "2026-06-26",
      time: "09:30", startLocation: "SRQ", destination: "Seattle", direction: "ROUND_TRIP", description: "",
    }), params(trip.id));
    expect(response.status).toBe(201);

    const segments = await prisma.travelSegment.findMany({ where: { tripId: trip.id }, orderBy: { position: "asc" } });
    expect(segments).toHaveLength(2);
    expect(segments[1]).toMatchObject({ startLocation: "Seattle", destination: "SRQ", returnForSegmentId: segments[0].id, autoGenerated: true });

    const populated = await patchSections(jsonRequest("PATCH", { action: "populateItinerary", mode: "add", confirm: false }), params(trip.id));
    expect(populated.status).toBe(200);
    expect(await prisma.itineraryItem.count({ where: { tripId: trip.id } })).toBe(2);

    await expect(prisma.travelSegment.create({ data: {
      tripId: trip.id, type: "Flight", title: "Duplicate", direction: "ONE_WAY", returnForSegmentId: segments[0].id,
    } })).rejects.toMatchObject({ code: "P2002" });
    await expect(prisma.travelSegment.create({ data: {
      tripId: trip.id, type: "Flight", title: "Dangling", direction: "ONE_WAY", returnForSegmentId: 999999,
    } })).rejects.toMatchObject({ code: "P2003" });
  });

  it("replays sequential schedule changes and independently restores date and time", async () => {
    const trip = await createTrip(state.userId);
    state.tripId = trip.id;
    const segment = await prisma.travelSegment.create({ data: {
      tripId: trip.id, type: "Flight", title: "Outbound", date: new Date("2026-06-27T00:00:00Z"), time: "09:00",
      startLocation: "SRQ", destination: "SEA",
    } });
    await prisma.itineraryItem.create({ data: {
      tripId: trip.id, sourceTravelSegmentId: segment.id, date: segment.date!, time: segment.time!, title: "Flight", description: "",
    } });

    const first = await postCommunity(jsonRequest("POST", {
      action: "update", updateType: "TRAVEL", updateKind: "SCHEDULE_CHANGE", travelSegmentId: segment.id,
      title: "Date change", content: "Moved one day", newDate: "2026-06-28", newTime: "",
    }), params(trip.id));
    const firstUpdate = (await first.json()).update;
    const second = await postCommunity(jsonRequest("POST", {
      action: "update", updateType: "TRAVEL", updateKind: "SCHEDULE_CHANGE", travelSegmentId: segment.id,
      title: "Time change", content: "Later flight", newDate: "", newTime: "11:30",
    }), params(trip.id));
    expect(second.status).toBe(201);

    const restored = await patchCommunity(jsonRequest("PATCH", {
      action: "update", updateId: firstUpdate.id, updateType: "TRAVEL", updateKind: "SCHEDULE_CHANGE",
      travelSegmentId: segment.id, title: "Date restored", content: "Use original date", newDate: "", newTime: "",
    }), params(trip.id));
    expect(restored.status).toBe(200);
    const final = await prisma.travelSegment.findUniqueOrThrow({ where: { id: segment.id } });
    expect(final.date?.toISOString().slice(0, 10)).toBe("2026-06-27");
    expect(final.time).toBe("11:30");
    expect((await prisma.itineraryItem.findFirstOrThrow({ where: { sourceTravelSegmentId: segment.id } })).time).toBe("11:30");
  });

  it("handles concurrent uploads and poll votes without duplicate identities", async () => {
    const trip = await createTrip(state.userId);
    state.tripId = trip.id;
    const upload = (name: string) => {
      const form = new FormData();
      form.set("file", new File([new TextEncoder().encode("%PDF-1.4\n%%EOF")], name, { type: "application/pdf" }));
      return uploadMedia(new Request("http://localhost/upload", { method: "POST", body: form }), { params: Promise.resolve({ id: String(trip.id), kind: "documents" }) });
    };
    const results = await Promise.all([upload("a.pdf"), upload("b.pdf")]);
    expect(results.every((result) => result.status === 201 || result.status === 500)).toBe(true);
    const documents = await prisma.tripDocument.findMany({ where: { tripId: trip.id } });
    expect(new Set(documents.map((item) => item.id)).size).toBe(documents.length);
    expect(documents.length).toBeGreaterThan(0);

    const photo = await prisma.tripPhoto.create({ data: {
      tripId: trip.id, name: "view.png", mimeType: "image/png", size: 8, data: new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]),
    } });
    const token = crypto.randomUUID();
    await prisma.trip.update({ where: { id: trip.id }, data: { shareToken: token, isPublished: true } });
    const publicPhoto = await getPublicMedia(new Request("http://localhost/photo"), {
      params: Promise.resolve({ token, kind: "photos", mediaId: String(photo.id) }),
    });
    expect(publicPhoto.status).toBe(200);

    const poll = await prisma.poll.create({ data: { tripId: trip.id, question: "Excursion?", options: { create: [{ label: "Yes" }] } }, include: { options: true } });
    const votes = await Promise.allSettled([
      prisma.pollVote.create({ data: { pollId: poll.id, optionId: poll.options[0].id, voterId: "same-voter" } }),
      prisma.pollVote.create({ data: { pollId: poll.id, optionId: poll.options[0].id, voterId: "same-voter" } }),
    ]);
    expect(votes.filter((vote) => vote.status === "fulfilled")).toHaveLength(1);
    expect(await prisma.pollVote.count({ where: { pollId: poll.id } })).toBe(1);
  });

  it("preserves concurrent travel updates and independent schedule changes", async () => {
    const trip = await createTrip(state.userId);
    state.tripId = trip.id;
    const segment = await prisma.travelSegment.create({ data: {
      tripId: trip.id, type: "Flight", title: "Outbound", date: new Date("2026-06-27T00:00:00Z"), time: "09:00",
    } });
    const requestUpdate = (body: Record<string, unknown>) => postCommunity(jsonRequest("POST", {
      action: "update", updateType: "TRAVEL", travelSegmentId: segment.id, ...body,
    }), params(trip.id));

    const informational = await Promise.all([
      requestUpdate({ updateKind: "INFORMATIONAL", title: "Gate", content: "Gate A" }),
      requestUpdate({ updateKind: "INFORMATIONAL", title: "Carrier", content: "Carrier confirmed" }),
    ]);
    expect(informational.every((response) => response.status === 201)).toBe(true);

    const schedule = await Promise.all([
      requestUpdate({ updateKind: "SCHEDULE_CHANGE", title: "Date", content: "Next day", newDate: "2026-06-28", newTime: "" }),
      requestUpdate({ updateKind: "SCHEDULE_CHANGE", title: "Time", content: "Later", newDate: "", newTime: "10:30" }),
    ]);
    expect(schedule.every((response) => response.status === 201)).toBe(true);
    expect(await prisma.tripUpdate.count({ where: { tripId: trip.id } })).toBe(4);
    const final = await prisma.travelSegment.findUniqueOrThrow({ where: { id: segment.id } });
    expect(final.date?.toISOString().slice(0, 10)).toBe("2026-06-28");
    expect(final.time).toBe("10:30");
  });
});
