ALTER TABLE "TripUpdate"
ADD COLUMN "updateKind" TEXT NOT NULL DEFAULT 'INFORMATIONAL',
ADD COLUMN "originalDate" TIMESTAMP(3),
ADD COLUMN "originalTime" TEXT,
ADD COLUMN "newDate" TIMESTAMP(3),
ADD COLUMN "newTime" TEXT;
