ALTER TABLE "Trip"
ADD COLUMN "tripDirection" TEXT NOT NULL DEFAULT 'ROUND_TRIP',
ADD COLUMN "returnNeedsRegeneration" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "TravelSegment"
ADD COLUMN "journey" TEXT NOT NULL DEFAULT 'OUTBOUND',
ADD COLUMN "position" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

WITH ranked AS (
  SELECT "id", ROW_NUMBER() OVER (PARTITION BY "tripId" ORDER BY "createdAt", "id") - 1 AS position
  FROM "TravelSegment"
)
UPDATE "TravelSegment"
SET "position" = ranked.position
FROM ranked
WHERE "TravelSegment"."id" = ranked."id";

CREATE INDEX "TravelSegment_tripId_journey_position_idx"
ON "TravelSegment"("tripId", "journey", "position");
