import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getOwnedTripId } from "@/lib/trip-access";
import {
  parseDateOnly,
  parseText,
  parseTripDirection,
  parseTripStatus,
  TRAVEL_SEGMENT_TYPES,
} from "@/lib/trips";

async function regenerateReturnSegments(tripId: number) {
  return prisma.$transaction(async (tx) => {
    const outbound = await tx.travelSegment.findMany({
      where: { tripId, journey: "OUTBOUND" },
      orderBy: [{ position: "asc" }, { id: "asc" }],
    });
    await tx.travelSegment.deleteMany({ where: { tripId, journey: "RETURN" } });
    if (outbound.length) {
      await tx.travelSegment.createMany({
        data: [...outbound].reverse().map((segment, position) => ({
          tripId,
          type: segment.type,
          title: segment.title,
          description: segment.description,
          date: segment.date,
          time: segment.time,
          startLocation: segment.destination,
          destination: segment.startLocation,
          journey: "RETURN",
          position,
          autoGenerated: true,
        })),
      });
    }
    await tx.trip.update({ where: { id: tripId }, data: { returnNeedsRegeneration: false } });
  });
}

async function ownedId(params: Promise<{ id: string }>) {
  const id = Number((await params).id);
  if (!Number.isInteger(id) || id < 1) return null;
  const owned = await getOwnedTripId(id);
  return owned.session && owned.tripId ? owned.tripId : null;
}

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const tripId = await ownedId(params);
  if (!tripId) return NextResponse.json({ error: "Trip not found" }, { status: 404 });

  const body = await request.json().catch(() => null);
  if (!body || typeof body.action !== "string") {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }

  if (body.action === "overview") {
    const description = parseText(body.description);
    const notes = parseText(body.notes);
    const destination = parseText(body.destination);
    const status = parseTripStatus(body.status);
    if (description === null || notes === null || destination === null || !status) {
      return NextResponse.json({ error: "Invalid overview" }, { status: 400 });
    }
    await prisma.trip.update({
      where: { id: tripId },
      data: { description, notes, destination, overviewStatus: status },
    });
  } else if (body.action === "travel") {
    const startLocation = parseText(body.startLocation);
    const destination = parseText(body.destination);
    const status = parseTripStatus(body.status);
    const tripDirection = parseTripDirection(body.tripDirection);
    if (startLocation === null || destination === null || !status || !tripDirection) {
      return NextResponse.json({ error: "Invalid travel details" }, { status: 400 });
    }
    await prisma.trip.update({
      where: { id: tripId },
      data: { startLocation, destination, travelStatus: status, tripDirection },
    });
    if (tripDirection === "ROUND_TRIP") {
      const returnCount = await prisma.travelSegment.count({ where: { tripId, journey: "RETURN" } });
      if (!returnCount) await regenerateReturnSegments(tripId);
    }
  } else if (body.action === "regenerateReturn") {
    const trip = await prisma.trip.findUnique({ where: { id: tripId }, select: { tripDirection: true } });
    if (trip?.tripDirection !== "ROUND_TRIP") {
      return NextResponse.json({ error: "Return journey is only available for round trips" }, { status: 400 });
    }
    const existingReturns = await prisma.travelSegment.count({ where: { tripId, journey: "RETURN" } });
    if (existingReturns && body.confirm !== true) {
      return NextResponse.json({ error: "Confirm regeneration before replacing existing return segments" }, { status: 409 });
    }
    await regenerateReturnSegments(tripId);
  } else if (body.action === "reorderSegment") {
    const itemId = Number(body.itemId);
    const direction = body.direction === "up" ? -1 : body.direction === "down" ? 1 : 0;
    if (!Number.isInteger(itemId) || !direction) {
      return NextResponse.json({ error: "Invalid segment order" }, { status: 400 });
    }
    const segments = await prisma.travelSegment.findMany({
      where: { tripId, journey: "OUTBOUND" },
      orderBy: [{ position: "asc" }, { id: "asc" }],
      select: { id: true, position: true },
    });
    const index = segments.findIndex((segment) => segment.id === itemId);
    const swapIndex = index + direction;
    if (index < 0 || swapIndex < 0 || swapIndex >= segments.length) {
      return NextResponse.json({ error: "Segment cannot be moved further" }, { status: 400 });
    }
    await prisma.$transaction([
      prisma.travelSegment.update({ where: { id: segments[index].id }, data: { position: segments[swapIndex].position } }),
      prisma.travelSegment.update({ where: { id: segments[swapIndex].id }, data: { position: segments[index].position } }),
      prisma.trip.update({ where: { id: tripId }, data: { returnNeedsRegeneration: true } }),
    ]);
  } else if (body.action === "populateItinerary") {
    const mode = body.mode === "replace" ? "replace" : body.mode === "add" ? "add" : null;
    if (!mode) {
      return NextResponse.json({ error: "Choose whether to add to or replace the itinerary" }, { status: 400 });
    }
    const [trip, segments, itineraryCount] = await Promise.all([
      prisma.trip.findUnique({ where: { id: tripId }, select: { startDate: true, endDate: true } }),
      prisma.travelSegment.findMany({
        where: { tripId },
        orderBy: [{ journey: "asc" }, { position: "asc" }, { id: "asc" }],
      }),
      prisma.itineraryItem.count({ where: { tripId } }),
    ]);
    if (!trip || !segments.length) {
      return NextResponse.json({ error: "Add travel segments before populating the itinerary" }, { status: 400 });
    }
    if (itineraryCount && body.confirm !== true) {
      return NextResponse.json({ error: "Confirm before changing an existing itinerary" }, { status: 409 });
    }
    await prisma.$transaction(async (tx) => {
      if (mode === "replace") {
        await tx.itineraryItem.deleteMany({ where: { tripId } });
      }
      await tx.itineraryItem.createMany({
        data: segments.map((segment) => ({
          tripId,
          date: segment.date ?? (segment.journey === "RETURN" ? trip.endDate : trip.startDate),
          time: segment.time || "00:00",
          title: `${segment.type}: ${segment.startLocation || "Start"} to ${segment.destination || "Destination"}`,
          description: [segment.title, segment.description].filter(Boolean).join("\n"),
        })),
      });
    });
  } else if (body.action === "sectionStatus") {
    const status = parseTripStatus(body.status);
    const fields = {
      itinerary: "itineraryStatus",
      documents: "documentsStatus",
      photos: "photosStatus",
    } as const;
    const field = fields[body.section as keyof typeof fields];
    if (!field || !status) {
      return NextResponse.json({ error: "Invalid section status" }, { status: 400 });
    }
    await prisma.trip.update({ where: { id: tripId }, data: { [field]: status } });
  } else if (body.action === "itinerary") {
    const itemId = Number(body.itemId);
    const date = parseDateOnly(body.date);
    const time = parseText(body.time, true);
    const title = parseText(body.title, true);
    const description = parseText(body.description);
    if (!Number.isInteger(itemId) || !date || !time || !title || description === null) {
      return NextResponse.json({ error: "Invalid itinerary item" }, { status: 400 });
    }
    const result = await prisma.itineraryItem.updateMany({
      where: { id: itemId, tripId },
      data: { date, time, title, description },
    });
    if (!result.count) return NextResponse.json({ error: "Item not found" }, { status: 404 });
  } else if (body.action === "segment") {
    const itemId = Number(body.itemId);
    const type = parseText(body.type, true);
    const title = parseText(body.title, true);
    const description = parseText(body.description);
    const date = body.date ? parseDateOnly(body.date) : null;
    const time = parseText(body.time) || null;
    const startLocation = parseText(body.startLocation);
    const destination = parseText(body.destination);
    if (!Number.isInteger(itemId) || !type || !title || description === null || startLocation === null || destination === null || (body.date && !date) || !TRAVEL_SEGMENT_TYPES.includes(type as never)) {
      return NextResponse.json({ error: "Invalid travel segment" }, { status: 400 });
    }
    const existing = await prisma.travelSegment.findFirst({ where: { id: itemId, tripId }, select: { journey: true } });
    if (!existing) return NextResponse.json({ error: "Segment not found" }, { status: 404 });
    const result = await prisma.travelSegment.updateMany({
      where: { id: itemId, tripId },
      data: { type, title, description, date, time, startLocation, destination, autoGenerated: false },
    });
    if (!result.count) return NextResponse.json({ error: "Segment not found" }, { status: 404 });
    if (existing.journey === "OUTBOUND") {
      await prisma.trip.update({ where: { id: tripId }, data: { returnNeedsRegeneration: true } });
    }
  } else {
    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  }

  return NextResponse.json({ success: true });
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const tripId = await ownedId(params);
  if (!tripId) return NextResponse.json({ error: "Trip not found" }, { status: 404 });
  const body = await request.json().catch(() => null);

  if (body?.action === "itinerary") {
    const date = parseDateOnly(body.date);
    const time = parseText(body.time, true);
    const title = parseText(body.title, true);
    const description = parseText(body.description);
    if (!date || !time || !title || description === null) {
      return NextResponse.json({ error: "Invalid itinerary item" }, { status: 400 });
    }
    const item = await prisma.itineraryItem.create({
      data: { tripId, date, time, title, description },
    });
    return NextResponse.json({ item }, { status: 201 });
  }

  if (body?.action === "segment") {
    const type = parseText(body.type, true);
    const title = parseText(body.title, true);
    const description = parseText(body.description);
    const date = body.date ? parseDateOnly(body.date) : null;
    const time = parseText(body.time) || null;
    const startLocation = parseText(body.startLocation);
    const destination = parseText(body.destination);
    if (!type || !title || description === null || startLocation === null || destination === null || (body.date && !date) || !TRAVEL_SEGMENT_TYPES.includes(type as never)) {
      return NextResponse.json({ error: "Invalid travel segment" }, { status: 400 });
    }
    const trip = await prisma.trip.findUnique({ where: { id: tripId }, select: { tripDirection: true } });
    if (!trip?.tripDirection) {
      return NextResponse.json({ error: "Choose One-Way or Round Trip before adding travel segments" }, { status: 400 });
    }
    const last = await prisma.travelSegment.aggregate({ where: { tripId, journey: "OUTBOUND" }, _max: { position: true } });
    const item = await prisma.travelSegment.create({
      data: { tripId, type, title, description, date, time, startLocation, destination, journey: "OUTBOUND", position: (last._max.position ?? -1) + 1 },
    });
    if (trip?.tripDirection === "ROUND_TRIP") {
      const returnCount = await prisma.travelSegment.count({ where: { tripId, journey: "RETURN" } });
      if (returnCount) {
        await prisma.trip.update({ where: { id: tripId }, data: { returnNeedsRegeneration: true } });
      } else {
        await regenerateReturnSegments(tripId);
      }
    }
    return NextResponse.json({ item }, { status: 201 });
  }

  return NextResponse.json({ error: "Invalid action" }, { status: 400 });
}

export async function DELETE(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const tripId = await ownedId(params);
  if (!tripId) return NextResponse.json({ error: "Trip not found" }, { status: 404 });
  const body = await request.json().catch(() => null);
  const itemId = Number(body?.itemId);
  if (!Number.isInteger(itemId)) {
    return NextResponse.json({ error: "Invalid item" }, { status: 400 });
  }

  const segment = body?.action === "segment"
    ? await prisma.travelSegment.findFirst({ where: { id: itemId, tripId }, select: { journey: true } })
    : null;
  const result = body?.action === "itinerary"
    ? await prisma.itineraryItem.deleteMany({ where: { id: itemId, tripId } })
    : body?.action === "segment"
      ? await prisma.travelSegment.deleteMany({ where: { id: itemId, tripId } })
      : null;

  if (!result?.count) return NextResponse.json({ error: "Item not found" }, { status: 404 });
  if (segment?.journey === "OUTBOUND") {
    await prisma.trip.update({ where: { id: tripId }, data: { returnNeedsRegeneration: true } });
  }
  return new Response(null, { status: 204 });
}
